### ISSUE TITLE
Post-installation test fails (with docker) due to file has no sequences defined (mode='rb')

### ISSUE THREAD

**Issue by kubu4** [EpiDiverse/wgbs#7]
Ran the following command to test installation:

`NXF_VER=20.07.1 /home/shared/nextflow run epidiverse/wgbs -profile test,docker`

The test fails in the following fashion:

```
[7f/7c58ce] process > INDEX:segemehl_indexing                       [100%] 1 of 1, cached: 1 ✔
[e5/b3c71d] process > WGBS:read_trimming (sampleB)                  [100%] 4 of 4 ✔
[ce/7db49f] process > WGBS:read_merging (sampleA)                   [100%] 2 of 2 ✔
[3a/e0cbeb] process > WGBS:fastqc (sampleB)                         [100%] 2 of 2 ✔
[a4/59a268] process > WGBS:erne_bs5 (sampleB)                       [100%] 2 of 2 ✔
[4e/a69ce3] process > WGBS:segemehl (sampleB)                       [100%] 2 of 2 ✔
[72/12a05b] process > WGBS:erne_bs5_processing (sampleB)            [100%] 2 of 2 ✔
[97/eee5d3] process > WGBS:segemehl_processing (sampleB)            [100%] 2 of 2 ✔
[d0/328879] process > WGBS:bam_merging (sampleB)                    [100%] 2 of 2 ✔
[08/d77720] process > WGBS:bam_subsetting (sampleB)                 [100%] 2 of 2 ✔
[86/ad52e2] process > WGBS:bam_filtering (sampleB - subset)         [ 83%] 5 of 6, failed: 3, retries: 2
[58/f9efef] process > WGBS:bam_statistics (sampleB)                 [100%] 4 of 4, failed: 4, retries: 2 ✔
[ef/ffb2e5] process > CALL:bam_processing (sampleB - lambda)        [100%] 2 of 2
[dd/325e85] process > CALL:Picard_MarkDuplicates (sampleA - lambda) [100%] 1 of 1
[-        ] process > CALL:MethylDackel                             -
[-        ] process > CALL:conversion_rate_estimation               -
Execution cancelled -- Finishing pending tasks before exit
Oops... Pipeline execution stopped with the following message: WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/home/sam/.nextflow/assets/epidiverse/wgbs/bin/filter_sam_uniqs.py", line 66, in <module>
    main(args.infile,args.ufile,args.mfile)
  File "/home/sam/.nextflow/assets/epidiverse/wgbs/bin/filter_sam_uniqs.py", line 35, in main
    with pysam.AlignmentFile(BAM, "rb") as original, pysam.AlignmentFile(UNIQ, "wb", header=original.header) as uniq, \
  File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 991, in pysam.libcalignmentfile.AlignmentFile._open
ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False
[9e/e439aa] NOTE: Process `WGBS:bam_statistics (sampleA)` terminated with an error exit status (1) -- Execution is retried (1)
[f8/7ebc98] NOTE: Process `WGBS:bam_filtering (sampleA - subset)` terminated with an error exit status (1) -- Execution is retried (1)
[91/f8e47f] NOTE: Process `WGBS:bam_statistics (sampleA)` terminated with an error exit status (1) -- Error is ignored
[a2/454bb8] NOTE: Process `WGBS:bam_statistics (sampleB)` terminated with an error exit status (1) -- Execution is retried (1)
[86/ad52e2] NOTE: Process `WGBS:bam_filtering (sampleB - subset)` terminated with an error exit status (1) -- Execution is retried (1)
[58/f9efef] NOTE: Process `WGBS:bam_statistics (sampleB)` terminated with an error exit status (1) -- Error is ignored
Error executing process > 'WGBS:bam_filtering (sampleA - subset)'

Caused by:
  Process `WGBS:bam_filtering (sampleA - subset)` terminated with an error exit status (1)

Command executed:

  mkdir sampleA sampleA/bam
  
  filter_sam_uniqs.py subset.bam sampleA/bam/unique.bam sampleA/bam/multimapped.bam
  ln -s sampleA/bam/unique.bam sampleA.bam

Command exit status:
  1

Command output:
  (empty)

Command error:
  WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
  Traceback (most recent call last):
    File "/home/sam/.nextflow/assets/epidiverse/wgbs/bin/filter_sam_uniqs.py", line 66, in <module>
      main(args.infile,args.ufile,args.mfile)
    File "/home/sam/.nextflow/assets/epidiverse/wgbs/bin/filter_sam_uniqs.py", line 35, in main
      with pysam.AlignmentFile(BAM, "rb") as original, pysam.AlignmentFile(UNIQ, "wb", header=original.header) as uniq, \
    File "pysam/libcalignmentfile.pyx", line 742, in pysam.libcalignmentfile.AlignmentFile.__cinit__
    File "pysam/libcalignmentfile.pyx", line 991, in pysam.libcalignmentfile.AlignmentFile._open
  ValueError: file has no sequences defined (mode='rb') - is it SAM/BAM format? Consider opening with check_sq=False

Work dir:
  /home/shared/8TB_HDD_01/sam/analyses/20220710-olu-epidiverse.wgbs/work/6f/d714bd306c2a32ce24f962d94a96e8

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out
```

Would you have any suggestions on how I might get past this to run the test command successfully?

**Comment by kubu4** [comment]
To add, this fails at the same point with the same error using the Singularity test profile as well.

**Comment by bio15anu** [comment]
Hmm, it is difficult to say but it looks like there could be a memory issue perhaps? At this stage of the pipeline it should be simply opening the `subset.bam` file for reading, in order to extract unique and multimapping alignments to new files. It claims that the `subset.bam` file is empty.

If you navigate to the work directory specified at the end of the returned error message, there should be a `subset.bam` file which you can open with samtools view. If it is indeed empty, then it may be a silent error from a previous process. You should then be able to follow the symbolic link to the previous work directory, and see if there are any error messages recorded there for example?

**Comment by kubu4** [comment]
Viewing the `subset.bam` file results in this error:

```shell
sam@raven:/home/shared/8TB_HDD_01/sam/analyses/20220710-olu-epidiverse.wgbs/work/6f/d714bd306c2a32ce24f962d94a96e8$ samtools view subset.bam | head
samtools view: error reading file "subset.bam": Numerical result out of range
```

If I follow the symlink, I end up in a directory with two BAMs:

```
J02459.1.bam  subset.bam
```

No other log files or anything.

Using `samtools view J02459.1.bam` looks like this:

```
1762_J02459.1:123-211   89      J02459.1        101     60      111M    *       0       -88     CTCTAAAAAAAAAAAAAACAACAAATACTAAAAACAAAACTTTTTAACCTCTATCATTTCCTTTCTCTATTTTTATCCATAAAATAAACAATAAAAATCAACAAAAAACAA 556778899:::;;<<===>>>???@@@AAAABBBCCCCCDDDDDEEEEEEEFFFFFFFFGGGGGGGGGGGGGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH      NM:i:0  NH:i:1  IH:i:1  HI:i:0  XB:Z:XX/XX      RG:Z:sampleA    PG:Z:ERNE
1762_J02459.1:123-211   137     J02459.1        124     60      111M    *       0       88      AATACTAAAAACAAAACTTTTTAACCTCTATCATTTCCTTTCTCTATTTTTATCCATAAAATAAACAATAAAAATCAACAAAAAACAACTAACTAACATTTTCAATTCAAA HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGGGGGGGGGGGGFFFFFFFFEEEEEEEDDDDDCCCCCBBBAAAA@@@???>>>===<<;;:::998877655      NM:i:1  NH:i:1  IH:i:1  HI:i:0  XB:Z:XX/XX      RG:Z:sampleA    PG:Z:ERNE
1673_J02459.1:174-326   99      J02459.1        174     60      111M    *       0       152     TGTTTGTGGAATGAATAATGGAAGTTAATAAAAAGTAGTTGGTTGATATTTTTGGTGTGAGTATTTGTATTATTTAGAATTGGTAGGAATAGGGAATGTTTGTTTTGTGAG HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHGGGGGGGGGGGGGGGFFFFFFFFEEEEEEEDDDDDCCCCCBBBAAAA@@@???>>>===<<;;:::998877655      NM:i:0  NH:i:1  IH:i:1  HI:i:0  XB:Z:XX/XX      RG:Z:sampleA    PG:Z:ERNE
```

**Comment by bio15anu** [comment]
Okay great, we're getting closer! Looks indeed like it could be a silent error in `WGBS:bam_subsetting`. From that directory which contains only `J02459.1.bam` and `subset.bam`, if you navigate up two levels in the directory structure, you should reach the base work directory for that process instance which contains hidden files such as `.command.log`, `.command.err` and `.command.out`. These might give us more clues as to what happened here to make `subset.bam` unreadable.

If not, try manually executing the code in `.command.sh` to see if you can recreate the problem.

**Comment by bio15anu** [comment]
Also I think there should be either a symbolic link to `sampleA.bam` or a `sampleB.bam` in that base work directory, if this file is also unreadable then the error probably occurred even earlier. In that case you can repeat the process of following back the symbolic link and investigating the log files in the previous work directory.

**Comment by bio15anu** [comment]
After further investigation, this seems solved now by simplifying [L458](https://github.com/EpiDiverse/wgbs/blob/17d09d16d859efd59e85a7bdf12c0924cba2b3ea/lib/wgbs.nf#L458) in [lib/wgbs.nf](https://github.com/EpiDiverse/wgbs/blob/17d09d16d859efd59e85a7bdf12c0924cba2b3ea/lib/wgbs.nf) as per [17d09d1](https://github.com/EpiDiverse/wgbs/commit/17d09d16d859efd59e85a7bdf12c0924cba2b3ea).

When running with Singularity/Docker, this was previously creating an empty header file which resulted in a truncated subset.bam file. This should also solve issue #11
